title: "RU5T_DR1FT"
description: "Les Codes du Royaume — fiction post-apocalyptique"
lang: fr
theme: minima

minima:
  skin: dark

exclude:
  - README.md
  - Test.txt
  - Test3.txt

header_pages:
  - index.md
  - episodes/index.md
  - presse/index.md